# Copyright 2021 Hewlett Packard Enterprise Development LP

nameOverride: kube-etcdbackup
fullnameOverride: kube-etcdbackup

image:
  repository: artifactory.algol60.net/csm-docker/stable/docker.io/roffe/kube-etcdbackup
  tag: v0.1.0
  pullPolicy: IfNotPresent

imagePullSecrets: []

schedule: '*/10 * * * *'

successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1
#
# Settings below are meant to prevent multiple
# pods in error state from overwhelming the system.
#
# To allow the job pod to be scheduled, we must set activeDeadlineSeconds in
# two places, and set the Pod's .spec.activeDeadlineSeconds
# to a higher value than the Job's .spec.activeDeadlineSeconds
# in order to prevent the pod from being killed prematurely.
#
jobActiveDeadlineSeconds: 300
podActiveDeadlineSeconds: 330
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 65534

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
