#
# MIT License
#
# (C) Copyright 2021, 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cray-baremetal-etcd-backup.fullname" . }}
  labels:
    {{- include "cray-baremetal-etcd-backup.labels" . | nindent 4 }}
spec:
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: {{ .Values.jobActiveDeadlineSeconds }}
      template:
        metadata:
          labels:
            {{- include "cray-baremetal-etcd-backup.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: {{ .Values.podActiveDeadlineSeconds }}
          containers:
          - name: {{ include "cray-baremetal-etcd-backup.name" . }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            envFrom:
            - configMapRef:
                name: kube-etcdbackup
            env:
              - name: S3_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: kube-etcdbackup-s3
                    key: S3_ACCESS_KEY
              - name: S3_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: kube-etcdbackup-s3
                    key: S3_SECRET_KEY
            volumeMounts:
            - name: etcd-client-certs
              mountPath: "/ssl"
              readOnly: true
          volumes:
          - name: etcd-client-certs
            secret:
              secretName: kube-etcdbackup-etcd
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
